name: syntheseus-full
channels:
  - defaults
  - conda-forge
  - pytorch
  - dglteam/label/th20_cu118  # LocalRetro, RetroKNN
dependencies:
  - dgl  # LocalRetro, RetroKNN
  - faiss-gpu     # RetroKNN
  - numpy
  - pip
  - python==3.9.7
  - pytorch=2.0.1
  - rdchiral_cpp  # MHNreact
  - rdkit=2021.09.4
